# Default configuration for ZT-3 Trading System

api:
  api_key: "your_upstox_api_key"
  api_secret: "your_upstox_api_secret"
  redirect_uri: "your_redirect_uri"
  api_version: "v2"

symbols:
  - ticker: "PNB"
    exchange: "NSE"

strategy:
  name: "GaussianChannel"
  params:
    # Gaussian Channel parameters from strategy.pine
    gc_source: "hlc3"
    gc_poles: 4
    gc_period: 144
    gc_multiplier: 1.2
    gc_reduced_lag_mode: false
    gc_fast_response_mode: false

    # Stochastic RSI parameters
    stoch_rsi_length: 14
    stoch_length: 14
    stoch_k_smooth: 3
    stoch_d_smooth: 3
    stoch_upper_band: 80.0

    # Volume filter
    use_volume_filter: true
    volume_ma_length: 20

    # Take profit and stop loss
    use_trailing_stop: false
    atr_length: 14
    atr_multiplier_tsl: 2.0
    use_take_profit: true
    atr_multiplier_tp: 4.0

risk:
  capital_percent: 95.0
  max_daily_loss: 5.0
  max_daily_trades: 5
  max_position_size: 100
  close_positions_eod: true

paper_trading:
  enabled: true
  starting_capital: 3000.0
  simulate_slippage: true
  slippage_percent: 0.1

execution:
  order_type: "MARKET" # MARKET, LIMIT
  slippage_tolerance: 0.1
  retry_attempts: 3
  retry_delay: 2

notifications:
  discord_webhooks:
    trade_alerts: ""
    performance: ""
    signals: ""
    system_status: ""
  notification_levels:
    trade_alerts: true
    performance: true
    signals: true
    system_status: true

logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/zt3.log"
  max_size_mb: 10
  backup_count: 5
