# Default Configuration for ZT-3 Trading System

# API Credentials
api:
  api_key: "${UPSTOX_API_KEY}" # Set via environment variable
  api_secret: "${UPSTOX_API_SECRET}" # Set via environment variable
  redirect_uri: "http://localhost:3000/callback" # Local redirect for OAuth flow

# Trading Symbols
symbols:
  - ticker: "PNB"
    exchange: "NSE"
    name: "Punjab National Bank"
    min_qty: 1
    tick_size: 0.05
    lot_size: 1
  - ticker: "CANBK"
    exchange: "NSE"
    name: "Canara Bank"
    min_qty: 1
    tick_size: 0.05
    lot_size: 1

# Strategy Configuration
strategy:
  name: "GaussianChannel"
  params:
    gc_period: 144
    gc_multiplier: 1.2
    stoch_rsi_length: 14
    stoch_length: 14
    stoch_k_smooth: 3
    stoch_upper_band: 80.0
    atr_length: 14
    atr_tp_multiplier: 4.0
    volume_ma_length: 20

# Risk Management Settings
risk:
  max_daily_loss: 5.0 # Percentage of capital
  max_daily_trades: 5
  capital_percent: 95.0 # Percentage of capital to allocate per trade
  circuit_breaker_enabled: true
  end_of_day_closure: true
  end_of_day_time: "15:15" # HH:MM in 24-hour format

# Paper Trading Settings
paper_trading:
  enabled: true
  starting_capital: 3000.0 # Initial paper trading capital
  simulate_slippage: true
  slippage_percent: 0.1
  commission_percent: 0.03

# Order Execution Settings
execution:
  order_type: "LIMIT"
  slippage_tolerance: 0.1
  retry_attempts: 3
  retry_delay: 2

# Notifications
notifications:
  discord:
    enabled: true
    webhooks:
      trade_alerts: "${DISCORD_WEBHOOK_TRADE_ALERTS}" # For buy/sell trade execution notifications
      performance: "${DISCORD_WEBHOOK_PERFORMANCE}" # For daily performance summaries
      signals: "${DISCORD_WEBHOOK_SIGNALS}" # For strategy signal notifications
      system_status: "${DISCORD_WEBHOOK_SYSTEM}" # For system health monitoring
      backtest_results: "${DISCORD_WEBHOOK_BACKTEST}" # For detailed backtest results
  notification_levels:
    trade_alerts: true
    performance: true
    signals: true
    system_status: true

# Logging
logging:
  level: "INFO"
  file: "logs/zt3.log"
  max_size_mb: 10
  backup_count: 5
  trade_log: "logs/trades.log"

# Data Storage
data:
  save_candles: true
  save_signals: true
  save_trades: true
  storage_path: "data/storage"
  cache_historical_data: true
