# Default Configuration for ZT-3 Trading System

# API Credentials
api:
  api_key: "${UPSTOX_API_KEY}" # Set via environment variable
  api_secret: "${UPSTOX_API_SECRET}" # Set via environment variable
  redirect_uri: "http://localhost:3000/callback" # Local redirect for OAuth flow

# Trading Symbols
symbols:
  - ticker: "PNB"
    exchange: "NSE"
    name: "Punjab National Bank"
    min_qty: 1
    tick_size: 0.05
    lot_size: 1
  # Add more symbols as needed
  - ticker: "CANBK"
    exchange: "NSE"
    name: "Canara Bank"
    min_qty: 1
    tick_size: 0.05
    lot_size: 1
  - ticker: "RVNL"
    exchange: "NSE"
    name: "Rail Vikas Nigam Limited"
    min_qty: 1
    tick_size: 0.05
    lot_size: 1

# Strategy identifier (Parameters are now hardcoded in the strategy class)
strategy:
  name: "SwingProStrategy" # Used by backtester/runner to load the correct class

# Risk Management Settings (These are system-level, not strategy-specific)
risk:
  max_daily_loss: 5.0 # Percentage of capital
  max_daily_trades: 10 # Increased limit
  # capital_percent: 95.0 # Removed - Strategy now calculates its own allocation %
  circuit_breaker_enabled: true
  end_of_day_closure: true # Close positions before market close
  end_of_day_time: "15:15" # HH:MM in 24-hour format

# Paper Trading Settings
paper_trading:
  enabled: true
  starting_capital: 3000.0 # Initial paper trading capital
  simulate_slippage: true
  slippage_percent: 0.1
  commission_percent: 0.03

# Order Execution Settings
execution:
  order_type: "LIMIT" # Or MARKET
  slippage_tolerance: 0.1 # For LIMIT orders, how far from current price
  retry_attempts: 3
  retry_delay: 2 # seconds

# Notifications
notifications:
  discord:
    enabled: true # Master switch for Discord notifications
    webhooks:
      trade_alerts: "${DISCORD_WEBHOOK_TRADE_ALERTS}" # For buy/sell trade execution notifications
      performance: "${DISCORD_WEBHOOK_PERFORMANCE}" # For daily performance summaries
      signals: "${DISCORD_WEBHOOK_SIGNALS}" # For strategy signal notifications (can be noisy)
      system_status: "${DISCORD_WEBHOOK_SYSTEM}" # For system health monitoring (startup, errors)
      backtest_results: "${DISCORD_WEBHOOK_BACKTEST}" # For detailed backtest results
  notification_levels: # Fine-grained control over which notifications are sent
    trade_alerts: true
    performance: true
    signals: false # Often too noisy, enable if needed
    system_status: true
    backtest_results: true # Send backtest summary

# Logging
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/zt3.log"
  max_size_mb: 10
  backup_count: 5
  trade_log: "logs/trades.log" # Separate log for executed trades

# Data Storage
data:
  save_candles: true # Save downloaded candle data
  save_signals: true # Save generated signals
  save_trades: true # Save executed trades (paper or live)
  storage_path: "data/storage" # Base directory for saved data
  cache_historical_data: true # Cache API data locally (implement caching logic if needed)

# Backtesting configuration (System-level settings for backtests)
backtest:
  starting_capital: 3000.0
  commission_percent: 0.03
  slippage_percent: 0.1
  max_concurrent_positions: 2 # Limit the number of simultaneous open trades
