# ZT-3 Trading System Configuration

# API credentials for Upstox
api:
  api_key: "your_upstox_api_key"
  api_secret: "your_upstox_api_secret"
  redirect_uri: "https://127.0.0.1:5000/callback" # For OAuth flow

# Symbols to monitor and trade
symbols:
  - ticker: "PNB"
    exchange: "NSE"
  - ticker: "SBIN"
    exchange: "NSE"
  - ticker: "BANKBARODA"
    exchange: "NSE"

# Strategy configuration
strategy:
  name: "GaussianChannel"
  params:
    # Gaussian Channel parameters
    gc_source: "hlc3" # Source for price calculation (hlc3, ohlc4, close)
    gc_poles: 4 # Number of poles for filter
    gc_period: 144 # Sampling period
    gc_multiplier: 1.2 # True range multiplier
    gc_reduced_lag_mode: false # Lag reduction mode
    gc_fast_response_mode: false # Fast response mode

    # Stochastic RSI parameters
    stoch_rsi_length: 14 # RSI length
    stoch_length: 14 # Stochastic length
    stoch_k_smooth: 3 # K line smoothing
    stoch_d_smooth: 3 # D line smoothing
    stoch_upper_band: 80.0 # Upper threshold

    # Volume filter
    use_volume_filter: true # Whether to use volume filter
    volume_ma_length: 20 # Volume MA period

    # Take profit and trailing stop
    atr_length: 14 # ATR period
    use_take_profit: true # Whether to use take profit
    atr_multiplier_tp: 4.0 # ATR multiplier for take profit
    use_trailing_stop: false # Whether to use trailing stop
    atr_multiplier_tsl: 2.0 # ATR multiplier for trailing stop

# Risk management settings
risk:
  capital_percent: 95.0 # Percentage of available capital to use per trade
  max_daily_loss: 5.0 # Maximum daily loss percentage
  max_daily_trades: 5 # Maximum number of trades per day
  circuit_breaker: true # Enable circuit breaker
  end_of_day_closure: true # Close all positions at end of day

# Paper trading settings
paper_trading:
  enabled: true # Start in paper trading mode by default
  starting_capital: 3000.0 # Initial capital
  simulate_slippage: true # Simulate slippage
  slippage_percent: 0.1 # Slippage percentage

# Execution settings
execution:
  order_type: "MARKET" # Order type (MARKET, LIMIT)
  slippage_tolerance: 0.1 # Slippage tolerance for limit orders
  retry_attempts: 3 # Number of retry attempts for failed orders
  retry_delay: 2 # Delay between retry attempts (seconds)

# Discord notification webhooks
notifications:
  discord_webhooks:
    trade_alerts: "webhook_url_for_trade_alerts"
    performance: "webhook_url_for_performance"
    signals: "webhook_url_for_signals"
    system_status: "webhook_url_for_system_status"
  notification_levels:
    trade_alerts: true
    performance: true
    signals: true
    system_status: true

# Logging settings
logging:
  level: "INFO" # Logging level (DEBUG, INFO, WARNING, ERROR)
  file: "logs/zt3.log" # Log file path
  max_size_mb: 10 # Maximum log file size in MB
  backup_count: 5 # Number of backup files to keep
  trade_log: "logs/trades.log" # Trade log file path
